name: therapy2go
static_sites:
  - name: frontend
    github:
      branch: uat
      deploy_on_push: true
    source_dir: /
    build_command: npm install && npm run build:frontend:uat
    output_dir: workspace/dist/apps/frontend/therapy2go-frontend
